"""Generate .github/CODEOWNERS from each specification's Document Control Owner.

MDG-001 chapter 09 makes the Owner in Document Control the steward of a specification. This
script makes that field operational: the person named there is the reviewer GitHub requests.

Run:
    python3 scripts/generate_codeowners.py           # rewrite .github/CODEOWNERS
    python3 scripts/generate_codeowners.py --check   # fail if the file is out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
CODEOWNERS = ROOT / ".github" / "CODEOWNERS"

OWNER_RE = re.compile(r"^\|\s*Owner\s*\|\s*(?P<owner>[^|]+?)\s*\|$", re.MULTILINE)
DOCUMENT_RE = re.compile(r"^Document: (?P<id>[A-Z]{3}-\d{3})$", re.MULTILINE)
TITLE_RE = re.compile(r"^\|\s*Title\s*\|\s*(?P<title>[^|]+?)\s*\|$", re.MULTILINE)
# An owner that names nobody accountable must not become a review assignment.
PLACEHOLDERS = {"", "tbd", "tbc", "todo", "unknown", "none", "n/a", "na", "owner", "unassigned", "git-username"}

HEADER = """# CODEOWNERS — generated by scripts/generate_codeowners.py. Do not edit by hand.
#
# Each entry derives from the Owner field in that specification's Document Control chapter,
# which MDG-001 chapter 09 defines as its steward. To change a reviewer, change the Owner in
# the specification and regenerate:
#
#     python3 scripts/generate_codeowners.py
#
# A specification whose Owner is a placeholder is deliberately absent: validate_docs.py fails
# on placeholder owners, so the gap is reported rather than silently assigned.

# Repository-wide fallback.
*                                       @AdamNi-7080

# Documentation standards and the tooling that enforces them.
/scripts/                               @AdamNi-7080
/templates/                             @AdamNi-7080
/.github/                               @AdamNi-7080
/CONTRIBUTING.md                        @AdamNi-7080
/chapter-registry.yml                   @AdamNi-7080
"""


def specifications() -> list[tuple[str, str, str, str]]:
    """Return (document id, title, repo-relative folder, owner) for every specification."""
    rows = []
    for control in sorted(DOCS.rglob("00-document-control.md")):
        text = control.read_text(encoding="utf-8")
        document = DOCUMENT_RE.search(text)
        owner = OWNER_RE.search(text)
        title = TITLE_RE.search(text)
        if not document or not owner:
            continue
        rows.append(
            (
                document.group("id"),
                title.group("title") if title else "",
                control.parent.relative_to(ROOT).as_posix(),
                owner.group("owner").strip(),
            )
        )
    return rows


def render() -> str:
    lines = [HEADER]
    skipped = []
    section = None
    for document, title, folder, owner in sorted(specifications()):
        if owner.lower() in PLACEHOLDERS:
            skipped.append((document, folder, owner))
            continue
        family = document.split("-")[0]
        if family != section:
            section = family
            lines.append(f"\n# {family} specifications")
        handle = owner if owner.startswith("@") else f"@{owner}"
        pattern = f"/{folder}/"
        # A pattern and its owner must be whitespace-separated, whatever the path length.
        lines.append(f"{pattern.ljust(72)} {handle}")

    if skipped:
        lines.append("\n# Unassigned — no reviewer can be derived until an Owner is recorded.")
        for document, folder, owner in skipped:
            lines.append(f"# {document}: /{folder}/ (Owner: {owner or 'missing'})")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if CODEOWNERS is out of date.")
    args = parser.parse_args()

    content = render()
    if args.check:
        current = CODEOWNERS.read_text(encoding="utf-8") if CODEOWNERS.is_file() else ""
        if current != content:
            print(
                "ERROR: .github/CODEOWNERS is out of date. "
                "Run python3 scripts/generate_codeowners.py",
                file=sys.stderr,
            )
            return 1
        print("CODEOWNERS is up to date.")
        return 0

    CODEOWNERS.parent.mkdir(parents=True, exist_ok=True)
    CODEOWNERS.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {CODEOWNERS.relative_to(ROOT).as_posix()} for {len(specifications())} specifications.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
