"""Report which specifications have been rewritten and which still need it.

Status is measured, not remembered. A rewritten specification leaves fingerprints: its
single-sentence paragraph ratio collapses, its uppercase RFC 2119 keywords disappear and its
code fences carry languages. Deriving status from the files means the tracker cannot go stale
when an agent forgets to tick a box.

Run:
    python3 scripts/rewrite_status.py            # print the table
    python3 scripts/rewrite_status.py --write    # regenerate review/rewrite-progress.md
"""

from __future__ import annotations

import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
TRACKER = ROOT / "review" / "rewrite-progress.md"

COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
FENCE_RE = re.compile(r"^```(.*)$", re.MULTILINE)
UPPER_RFC_RE = re.compile(r"\b(?:MUST NOT|MUST|SHALL NOT|SHALL|SHOULD NOT|SHOULD|MAY)\b")
MERMAID_RE = re.compile(r"^```mermaid", re.MULTILINE)

# A rewritten specification lands well below this; an untouched one sits at or near 100%.
# MEG-004 went from 100% to 64%, so 85% separates the two populations with room to spare.
REWRITTEN_BELOW = 85


@dataclass
class Spec:
    document: str
    folder: Path
    lines: int
    words: int
    paragraphs: int
    single: int
    upper_rfc: int
    bare_fences: int
    mermaid: int
    last_touched: str

    @property
    def single_pct(self) -> int:
        return self.single * 100 // max(self.paragraphs, 1)

    @property
    def done(self) -> bool:
        return self.single_pct < REWRITTEN_BELOW

    @property
    def effort(self) -> int:
        """Rough size of the remaining job: lines still carrying staccato prose."""
        return 0 if self.done else self.lines


def last_commit(folder: Path) -> str:
    result = subprocess.run(
        ["git", "log", "-1", "--format=%h %ad", "--date=short", "--", folder.as_posix()],
        cwd=ROOT, capture_output=True, text=True, encoding="utf-8",
    )
    return result.stdout.strip() or "—"


def measure(folder: Path) -> Spec | None:
    control = folder / "00-document-control.md"
    if not control.is_file():
        return None
    document = ""
    match = re.search(r"^Document: (\S+)", control.read_text(encoding="utf-8"), re.MULTILINE)
    if match:
        document = match.group(1)

    lines = words = paragraphs = single = upper = bare = mermaid = 0
    for path in folder.rglob("*.md"):
        text = path.read_text(encoding="utf-8")
        lines += len(text.splitlines())
        stripped = COMMENT_RE.sub("", text)
        words += len(re.findall(r"[A-Za-z][A-Za-z'-]+", stripped))
        upper += len(UPPER_RFC_RE.findall(stripped))
        mermaid += len(MERMAID_RE.findall(text))
        # Only an opening fence can lack a language; a closing fence is always bare, so
        # counting every bare marker would report roughly one per code block.
        in_fence = False
        for line in text.splitlines():
            if not line.startswith("```"):
                continue
            if not in_fence and not line[3:].strip():
                bare += 1
            in_fence = not in_fence
        for block in re.split(r"\n\s*\n", stripped):
            block = block.strip()
            if not block or block[0] in "#|->`*" or re.match(r"^\d+\.", block):
                continue
            paragraphs += 1
            if len(re.findall(r"[.!?](\s|$)", block)) <= 1:
                single += 1

    return Spec(document or folder.name.upper(), folder, lines, words, paragraphs,
                single, upper, bare, mermaid, last_commit(folder))


def collect() -> list[Spec]:
    specs = [s for f in sorted(DOCS.rglob("00-document-control.md")) if (s := measure(f.parent))]
    return sorted(specs, key=lambda s: (s.done, -s.effort, s.document))


def render(specs: list[Spec]) -> str:
    done = [s for s in specs if s.done]
    todo = [s for s in specs if not s.done]
    remaining_lines = sum(s.lines for s in todo)
    total_lines = sum(s.lines for s in specs)

    out = [
        "# Rewrite Progress",
        "",
        "**Temporary working file.** Delete it once every specification is rewritten; it tracks a"
        " migration, not a standing property of the repository.",
        "",
        "Generated by `python3 scripts/rewrite_status.py --write`. Do not edit by hand — status is"
        " measured from the files themselves, so a hand-edited tick would be overwritten and a"
        " forgotten one would not matter.",
        "",
        "## How status is decided",
        "",
        "A specification counts as rewritten when fewer than "
        f"{REWRITTEN_BELOW}% of its prose paragraphs are a single sentence. Untouched"
        " specifications sit at or near 100%; MEG-004 landed at 64% after its rewrite, so the"
        " threshold separates the two populations without needing a manual flag.",
        "",
        "The other columns size the remaining job: `RFC` counts uppercase RFC 2119 keywords that"
        " MDG-001 chapter 10 says should be sentence case, and `Bare` counts code fences with no"
        " language, which markdownlint reports as MD040.",
        "",
        "A small non-zero `RFC` count can be legitimate: a Normative Language table that *defines* the RFC 2119 keywords keeps them uppercase, because lowercasing there would destroy its meaning. MEG-004 retains five for that reason.",
        "",
        "## For agents",
        "",
        "1. Take the top unfinished specification unless told otherwise. The table is ordered by"
        " size of remaining work.",
        "2. Rewrite it, then run `python3 scripts/prose_audit.py <folder>` and confirm it passes.",
        "3. Record anything you could not resolve without inventing facts in"
        " [open-questions.md](open-questions.md).",
        "4. Regenerate this file with `python3 scripts/rewrite_status.py --write` and commit it"
        " alongside the rewrite.",
        "5. Never use `git stash` — other agents may hold uncommitted work. Use"
        " `git show HEAD:<path>` to read the committed version of a file.",
        "",
        "## Summary",
        "",
        f"- **{len(done)} of {len(specs)} specifications meet the prose standard**",
        f"- {total_lines - remaining_lines:,} of {total_lines:,} lines done"
        f" ({(total_lines - remaining_lines) * 100 // max(total_lines, 1)}%)",
        f"- {remaining_lines:,} lines remaining across {len(todo)} specifications",
        "",
        "## Needs rewriting",
        "",
        "| Document | Lines | Single-sentence | RFC | Bare | Diagrams | Folder |",
        "|----------|------:|----------------:|----:|-----:|---------:|--------|",
    ]
    for s in todo:
        rel = s.folder.relative_to(DOCS).as_posix()
        out.append(
            f"| {s.document} | {s.lines:,} | {s.single_pct}% | {s.upper_rfc} | {s.bare_fences} "
            f"| {s.mermaid} | `{rel}` |"
        )

    out += ["", "## Meeting the standard", "",
            "Includes both specifications rewritten by this migration and short documents that"
            " already conformed — decision records, protocol outlines and superseded stubs.", "",
            "| Document | Lines | Single-sentence | RFC | Bare | Diagrams | Last commit |",
            "|----------|------:|----------------:|----:|-----:|---------:|-------------|"]
    for s in done:
        out.append(
            f"| {s.document} | {s.lines:,} | {s.single_pct}% | {s.upper_rfc} | {s.bare_fences} "
            f"| {s.mermaid} | {s.last_touched} |"
        )
    if not done:
        out.append("| — | | | | | | |")

    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate review/rewrite-progress.md")
    args = parser.parse_args()

    specs = collect()
    content = render(specs)
    if args.write:
        TRACKER.parent.mkdir(parents=True, exist_ok=True)
        TRACKER.write_text(content, encoding="utf-8", newline="\n")
        done = sum(1 for s in specs if s.done)
        print(f"Wrote {TRACKER.relative_to(ROOT).as_posix()} — {done}/{len(specs)} meeting the standard.")
    else:
        print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
